function(mcp_define_tristate NAME DEFAULT_VALUE HELP_TEXT)
    set(${NAME} "${DEFAULT_VALUE}" CACHE STRING "${HELP_TEXT}")
    set_property(CACHE ${NAME} PROPERTY STRINGS y m n)
endfunction()

function(mcp_define_bool NAME DEFAULT_VALUE HELP_TEXT)
    set(${NAME} "${DEFAULT_VALUE}" CACHE BOOL "${HELP_TEXT}")
endfunction()

function(mcp_apply_kconfig_bool SYMBOL NAME VALUE)
    if("${VALUE}" STREQUAL "y")
        set(${NAME} ON CACHE BOOL "" FORCE)
    elseif("${VALUE}" STREQUAL "n")
        set(${NAME} OFF CACHE BOOL "" FORCE)
    else()
        message(FATAL_ERROR "${SYMBOL} is bool and only accepts y or not set, got: ${VALUE}")
    endif()
endfunction()

function(mcp_apply_kconfig_tristate SYMBOL NAME VALUE)
    if("${VALUE}" STREQUAL "y" OR "${VALUE}" STREQUAL "m" OR "${VALUE}" STREQUAL "n")
        set(${NAME} "${VALUE}" CACHE STRING "" FORCE)
        set_property(CACHE ${NAME} PROPERTY STRINGS y m n)
    else()
        message(FATAL_ERROR "${SYMBOL} is tristate and only accepts y, m, or not set, got: ${VALUE}")
    endif()
endfunction()

function(mcp_apply_kconfig_builtin_tool SYMBOL NAME VALUE)
    if("${VALUE}" STREQUAL "y" OR "${VALUE}" STREQUAL "n")
        set(${NAME} "${VALUE}" CACHE STRING "" FORCE)
        set_property(CACHE ${NAME} PROPERTY STRINGS y m n)
    else()
        message(FATAL_ERROR "${SYMBOL} is built into mcp_server and only accepts y or not set, got: ${VALUE}")
    endif()
endfunction()

function(mcp_apply_tcp_security VALUE)
    if("${VALUE}" STREQUAL "mtls" OR "${VALUE}" STREQUAL "plaintext")
        set(MCP_TCP_SECURITY "${VALUE}" CACHE STRING "" FORCE)
        set_property(CACHE MCP_TCP_SECURITY PROPERTY STRINGS mtls plaintext)
    else()
        message(FATAL_ERROR
            "CONFIG_MCP_TCP_SECURITY only accepts mtls or plaintext, got: ${VALUE}")
    endif()
endfunction()

function(mcp_apply_kconfig_forced_builtin SYMBOL VALUE)
    if(NOT "${VALUE}" STREQUAL "y")
        message(FATAL_ERROR "${SYMBOL} is a required built-in feature and must be y")
    endif()
endfunction()

function(mcp_apply_kconfig_symbol SYMBOL VALUE)
    if("${SYMBOL}" STREQUAL "CONFIG_MCP_SERVER_CORE" OR
       "${SYMBOL}" STREQUAL "CONFIG_MCP_PLUGIN_MANAGER_CORE" OR
       "${SYMBOL}" STREQUAL "CONFIG_MCP_TOOL_SERVER_DISCOVERY")
        mcp_apply_kconfig_forced_builtin("${SYMBOL}" "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_TRANSPORT_STDIO")
        mcp_apply_kconfig_bool("${SYMBOL}" MCP_TRANSPORT_STDIO "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_TRANSPORT_UDP")
        mcp_apply_kconfig_bool("${SYMBOL}" MCP_TRANSPORT_UDP "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_TCP_SECURITY")
        mcp_apply_tcp_security("${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_BUILD_TESTS")
        mcp_apply_kconfig_bool("${SYMBOL}" MCP_BUILD_TESTS "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_BUILD_EMBEDDED_EXAMPLES")
        mcp_apply_kconfig_bool("${SYMBOL}" MCP_BUILD_EMBEDDED_EXAMPLES "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_USE_BUNDLED_LIBUV")
        mcp_apply_kconfig_bool("${SYMBOL}" MCP_USE_BUNDLED_LIBUV "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_USE_BUNDLED_JANSSON")
        mcp_apply_kconfig_bool("${SYMBOL}" MCP_USE_BUNDLED_JANSSON "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_USE_SYSTEM_LIBUV")
        mcp_apply_kconfig_bool("${SYMBOL}" MCP_USE_SYSTEM_LIBUV "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_USE_SYSTEM_JANSSON")
        mcp_apply_kconfig_bool("${SYMBOL}" MCP_USE_SYSTEM_JANSSON "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_TOOL_SYSTEM")
        mcp_apply_kconfig_builtin_tool("${SYMBOL}" MCP_TOOL_SYSTEM "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_TOOL_GATEWAY")
        mcp_apply_kconfig_builtin_tool("${SYMBOL}" MCP_TOOL_GATEWAY "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_TOOL_REGISTRY")
        mcp_apply_kconfig_builtin_tool("${SYMBOL}" MCP_TOOL_REGISTRY "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_TOOL_PLUGIN_MANAGER")
        mcp_apply_kconfig_builtin_tool("${SYMBOL}" MCP_TOOL_PLUGIN_MANAGER "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_TOOL_EMBEDDED")
        mcp_apply_kconfig_builtin_tool("${SYMBOL}" MCP_TOOL_EMBEDDED "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_TOOL_REMOTE")
        mcp_apply_kconfig_builtin_tool("${SYMBOL}" MCP_TOOL_REMOTE "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_TOOL_AGENT")
        mcp_apply_kconfig_builtin_tool("${SYMBOL}" MCP_TOOL_AGENT "${VALUE}")
    elseif("${SYMBOL}" STREQUAL "CONFIG_MCP_FILE_TRANSFER_PLUGIN")
        mcp_apply_kconfig_tristate("${SYMBOL}" MCP_FILE_TRANSFER_PLUGIN "${VALUE}")
    endif()
endfunction()

function(mcp_load_kconfig_options)
    set(MCP_KCONFIG_CONFIG "" CACHE FILEPATH "Linux-style MCP .config file")

    if(MCP_KCONFIG_CONFIG)
        set(_mcp_kconfig "${MCP_KCONFIG_CONFIG}")
        if(NOT IS_ABSOLUTE "${_mcp_kconfig}")
            get_filename_component(_mcp_kconfig "${_mcp_kconfig}" ABSOLUTE BASE_DIR "${PROJECT_SOURCE_DIR}")
        endif()
    else()
        return()
    endif()

    if(NOT EXISTS "${_mcp_kconfig}")
        message(FATAL_ERROR "MCP_KCONFIG_CONFIG does not exist: ${_mcp_kconfig}")
    endif()

    file(STRINGS "${_mcp_kconfig}" _mcp_kconfig_lines)
    foreach(_mcp_line IN LISTS _mcp_kconfig_lines)
        if("${_mcp_line}" MATCHES "^[ \t]*CONFIG_([A-Za-z0-9_]+)=(.*)$")
            set(_mcp_symbol "CONFIG_${CMAKE_MATCH_1}")
            set(_mcp_value "${CMAKE_MATCH_2}")
            string(STRIP "${_mcp_value}" _mcp_value)
            string(REGEX REPLACE "^\"(.*)\"$" "\\1" _mcp_value "${_mcp_value}")
            mcp_apply_kconfig_symbol("${_mcp_symbol}" "${_mcp_value}")
        elseif("${_mcp_line}" MATCHES "^[ \t]*# CONFIG_([A-Za-z0-9_]+) is not set")
            set(_mcp_symbol "CONFIG_${CMAKE_MATCH_1}")
            mcp_apply_kconfig_symbol("${_mcp_symbol}" "n")
        endif()
    endforeach()

    message(STATUS "Loaded MCP Kconfig options from ${_mcp_kconfig}")
endfunction()

function(mcp_load_default_options)
    mcp_define_bool(MCP_TRANSPORT_STDIO ON "Enable stdio transport")
    mcp_define_bool(MCP_TRANSPORT_UDP OFF "Enable UDP transport placeholder")
    set(MCP_TCP_SECURITY "mtls" CACHE STRING "TCP security: mtls or plaintext")
    set_property(CACHE MCP_TCP_SECURITY PROPERTY STRINGS mtls plaintext)
    mcp_define_bool(MCP_BUILD_TESTS ON "Build protocol smoke tests")
    mcp_define_bool(MCP_BUILD_EMBEDDED_EXAMPLES OFF "Build embedded examples")

    mcp_define_tristate(MCP_TOOL_SYSTEM "y" "system tools: y/m/n")
    mcp_define_tristate(MCP_TOOL_GATEWAY "y" "gateway tools: y/m/n")
    mcp_define_tristate(MCP_TOOL_REGISTRY "y" "registry tools: y/m/n")
    mcp_define_tristate(MCP_TOOL_PLUGIN_MANAGER "y" "plugin manager tools: y/m/n")
    mcp_define_tristate(MCP_TOOL_EMBEDDED "y" "embedded proxy tools: y/m/n")
    mcp_define_tristate(MCP_TOOL_REMOTE "n" "remote proxy tools: y/m/n")
    mcp_define_tristate(MCP_TOOL_AGENT "n" "agent tools: y/m/n")
    mcp_define_tristate(MCP_FILE_TRANSFER_PLUGIN "m" "file transfer plugin: y/m/n")
endfunction()

function(mcp_validate_tcp_security)
    if(NOT (MCP_TCP_SECURITY STREQUAL "mtls" OR MCP_TCP_SECURITY STREQUAL "plaintext"))
        message(FATAL_ERROR
            "MCP_TCP_SECURITY must be mtls or plaintext, got: ${MCP_TCP_SECURITY}")
    endif()
    message(STATUS "MCP TCP security build mode: ${MCP_TCP_SECURITY}")
endfunction()
