function(mcp_define_tristate NAME DEFAULT_VALUE HELP_TEXT)
    set(${NAME} "${DEFAULT_VALUE}" CACHE STRING "${HELP_TEXT}")
    set_property(CACHE ${NAME} PROPERTY STRINGS y m n)
endfunction()

function(mcp_load_default_options)
    option(MCP_TRANSPORT_STDIO "Enable stdio transport" ON)
    option(MCP_TRANSPORT_UDP "Enable UDP transport placeholder" OFF)
    option(MCP_BUILD_TESTS "Build protocol smoke tests" ON)
    option(MCP_BUILD_EMBEDDED_EXAMPLES "Build embedded examples" OFF)

    mcp_define_tristate(MCP_TOOL_SYSTEM "y" "system tools: y/m/n")
    mcp_define_tristate(MCP_TOOL_GATEWAY "y" "gateway tools: y/m/n")
    mcp_define_tristate(MCP_TOOL_REGISTRY "y" "registry tools: y/m/n")
    mcp_define_tristate(MCP_TOOL_PLUGIN_MANAGER "y" "plugin manager tools: y/m/n")
    mcp_define_tristate(MCP_TOOL_EMBEDDED "y" "embedded proxy tools: y/m/n")
    mcp_define_tristate(MCP_TOOL_REMOTE "n" "remote proxy tools: y/m/n")
    mcp_define_tristate(MCP_TOOL_AGENT "n" "agent tools: y/m/n")
endfunction()
