function(mcp_detect_platform)
    if(WIN32)
        set(MCP_PLATFORM_WINDOWS TRUE PARENT_SCOPE)
        message(STATUS "MCP platform: Windows")
    elseif(UNIX AND NOT APPLE)
        set(MCP_PLATFORM_LINUX TRUE PARENT_SCOPE)
        if(CMAKE_CROSSCOMPILING)
            set(MCP_PLATFORM_CROSS_COMPILED TRUE PARENT_SCOPE)
            message(STATUS "MCP platform: Linux (${CMAKE_SYSTEM_PROCESSOR}, cross-compiled)")
        else()
            message(STATUS "MCP platform: Linux")
        endif()
    else()
        message(WARNING "MCP platform: unsupported or experimental")
    endif()
endfunction()
