function(mcp_detect_platform)
    if(WIN32)
        set(MCP_PLATFORM_WINDOWS TRUE PARENT_SCOPE)
        message(STATUS "MCP platform: Windows")
    elseif(UNIX AND NOT APPLE)
        set(MCP_PLATFORM_LINUX TRUE PARENT_SCOPE)
        message(STATUS "MCP platform: Linux")
    else()
        message(WARNING "MCP platform: unsupported or experimental")
    endif()
endfunction()
